UserName: wing.nus@gmail.com
Password: csiscdtlLIFT-15
UserId: 105956
phantomjsPath: 'C:/Users/workshop/Downloads/phantomjs-2.1.1-windows/bin/phantomjs.exe'
database_path: C:/Users/workshop/Desktop/Projects/Wikifier-master/server-master/courseraD.db