
from scrapy.item import Item, Field


# class EDXItem(scrapy.Item):
#     number = scrapy.Field()
#     key = scrapy.Field()
#     title = scrapy.Field()
#     short_description = scrapy.Field()
#     full_description = scrapy.Field()
#     level_type = scrapy.Field()
#     marketing_url = scrapy.Field()
#     enrollment_start = scrapy.Field()
#     enrollment_end = scrapy.Field()
#     end = scrapy.Field()
#     start = scrapy.Field()
#     org = scrapy.Field()
#     length = scrapy.Field()
#     effort = scrapy.Field()
#     prerequisites = scrapy.Field()
#     pacing_type = scrapy.Field()
#     published = scrapy.Field()
#     language = scrapy.Field()
#     transcript_languages = scrapy.Field()
#     availability = scrapy.Field()
#     program_types = scrapy.Field()
#     rating = scrapy.Field()
#     review_count = scrapy.Field()
#     instructor_1 = scrapy.Field()
#     instructor_2 = scrapy.Field()
#     instructor_3 = scrapy.Field()
#     instructor_4 = scrapy.Field()
#     instructor_5 = scrapy.Field()
#     org_instructor_1 = scrapy.Field()
#     org_instructor_2 = scrapy.Field()
#     org_instructor_3 = scrapy.Field()
#     org_instructor_4 = scrapy.Field()
#     org_instructor_5 = scrapy.Field()

class EDXItem(Item):
    number = Field()
    key = Field()
    title = Field()
    short_description = Field()
    full_description = Field()
    level_type = Field()
    marketing_url = Field()
    enrollment_start = Field()
    enrollment_end = Field()
    end = Field()
    start = Field()
    org = Field()
    length = Field()
    effort = Field()
    prerequisites = Field()
    pacing_type = Field()
    published = Field()
    language = Field()
    transcript_languages = Field()
    availability = Field()
    program_types = Field()
    rating = Field()
    review_count = Field()
    instructor_1 = Field()
    instructor_2 = Field()
    instructor_3 = Field()
    instructor_4 = Field()
    instructor_5 = Field()
    org_instructor_1 = Field()
    org_instructor_2 = Field()
    org_instructor_3 = Field()
    org_instructor_4 = Field()
    org_instructor_5 = Field()
